name: Main Github Workflow

on:
  push:
    branches: [main,aidan-branch]
  pull_request:
    branches: [main,aidan-branch]

jobs:
  build_and_test:
    name: Build App and Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permissions for Gradle
        run: chmod +x ./gradlew

      - name: Building App
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --tests "com.theateam.sparklinehr.LeaveRequestTests"