name: Security and Static Code Analysis Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static_analysis:
    name: Security and Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Python and GitGuardian CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install ggshield

      - name: Check ggshield Version
        run: ggshield --version

      - name: Run GitGuardian Security Scan
        run: ggshield secret scan repo .
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: Set Execute Permissions for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run Static Code Scan with Lint
        run: ./gradlew lint
